# Generated by Django 4.1.2 on 2022-10-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
