# Generated by Django 4.1.2 on 2022-10-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0002_rename_users_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
