# Generated by Django 4.1.1 on 2022-10-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0005_reserva_delete_reservas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
