# Generated by Django 4.1.1 on 2022-10-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0009_reserva_fimdate_alter_reserva_inidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fimdate',
            field=models.DateTimeField(default='2002-08-11'),
        ),
    ]
