# Generated by Django 4.1.1 on 2022-10-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0010_alter_reserva_fimdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fimdate',
            field=models.DateTimeField(default='2002-08-11 00:00:00'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='inidate',
            field=models.DateTimeField(default='2002-08-10 00:00:00'),
        ),
    ]
