# Generated by Django 4.1.1 on 2022-10-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0011_alter_reserva_fimdate_alter_reserva_inidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fimdate',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='inidate',
            field=models.DateTimeField(default=''),
        ),
    ]
