# Generated by Django 4.1.1 on 2022-10-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0014_alter_estabelecimento_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lugares', models.IntegerField(null=True)),
            ],
        ),
    ]
