# Generated by Django 4.1.1 on 2022-10-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0016_praiaequipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='praiaequipamento',
            name='equipamentos',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='praiaequipamento',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
