# Generated by Django 4.1.1 on 2022-10-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0018_alter_praiaequipamento_equipamentos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='praiaequipamento',
            old_name='equipamentos',
            new_name='stock',
        ),
    ]
