# Generated by Django 4.1.1 on 2022-10-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0019_rename_equipamentos_praiaequipamento_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praiaequipamento',
            name='stock',
        ),
    ]
