# Generated by Django 4.1.1 on 2022-10-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0020_remove_praiaequipamento_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='praiaequipamento',
            name='lugares',
            field=models.IntegerField(null=True),
        ),
    ]
