# Generated by Django 4.1.1 on 2022-10-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0021_praiaequipamento_lugares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praiaequipamento',
            name='lugares',
        ),
    ]
