# Generated by Django 4.1.1 on 2022-10-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0022_remove_praiaequipamento_lugares'),
    ]

    operations = [
        migrations.AddField(
            model_name='praiaequipamento',
            name='stock',
            field=models.IntegerField(default=500),
        ),
    ]
