# Generated by Django 4.1.1 on 2022-10-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0027_praia_delete_praiaequipamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praia',
            name='type',
        ),
    ]
