# Generated by Django 4.1.1 on 2022-10-18 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basedailym8', '0029_alter_praia_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamento',
            name='EstEstabelecimento',
            field=models.ManyToManyField(blank=True, null=True, to='basedailym8.estabelecimento'),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='reserva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedailym8.reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
