# Generated by Django 4.1.1 on 2022-10-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0030_estacionamento_estestabelecimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='EstEstabelecimento',
            field=models.ManyToManyField(blank=True, to='basedailym8.estabelecimento'),
        ),
    ]
