# Generated by Django 4.1.1 on 2022-10-18 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basedailym8', '0031_alter_estacionamento_estestabelecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='user',
        ),
        migrations.AddField(
            model_name='reserva',
            name='User',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
