# Generated by Django 4.1.1 on 2022-10-18 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basedailym8', '0032_remove_reserva_user_reserva_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='User',
        ),
        migrations.AddField(
            model_name='reserva',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
