# Generated by Django 4.1.1 on 2022-10-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0033_remove_reserva_user_reserva_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamento',
            name='EstEstabelecimento',
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='EstEstabelecimento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedailym8.estabelecimento'),
        ),
    ]
