# Generated by Django 4.1.2 on 2022-10-20 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basedailym8', '0034_remove_estacionamento_estestabelecimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedailym8.reserva'),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='EstEstabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedailym8.estabelecimento'),
        ),
        migrations.AlterField(
            model_name='praia',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedailym8.reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
