# Generated by Django 4.1.1 on 2022-10-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0035_alter_estabelecimento_reserva_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estabelecimento',
            new_name='Spot',
        ),
    ]
