# Generated by Django 4.1.1 on 2022-10-23 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0036_rename_estabelecimento_spot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='reserva',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedailym8.spot'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='type',
            field=models.CharField(choices=[('reserva_almoco', 'Almoço'), ('reserva_lanche', 'Lanche'), ('reserva_jantar', 'Jantar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='spot',
            name='type',
            field=models.CharField(choices=[('spot_restaurante', 'Restaurante'), ('spot_bar', 'Bar'), ('spot_cafe', 'Cafe')], max_length=20),
        ),
    ]
