# Generated by Django 4.1.1 on 2022-10-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0037_remove_spot_reserva_alter_reserva_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='type',
            field=models.CharField(choices=[('Restaurante', 'spot_restaurante'), ('Bar', 'spot_bar'), ('Cafe', 'spot_cafe')], max_length=20),
        ),
    ]
