# Generated by Django 4.1.1 on 2022-10-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0038_alter_spot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='type',
            field=models.CharField(choices=[('Almoço', 'reserva_almoco'), ('Lanche', 'reserva_lanche'), ('Jantar', 'reserva_jantar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='spot',
            name='type',
            field=models.CharField(choices=[('Restaurante', 'spot_restaurante'), ('Bar', 'spot_bar'), ('Cafe', 'spot_cafe'), ('Discoteca', 'spot_disco'), ('Bar de Praia', 'spot_bardepraia')], max_length=20),
        ),
    ]
