# Generated by Django 4.1.1 on 2022-11-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0043_pratos_remove_estacionamento_estestabelecimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='releasedate',
            field=models.DateTimeField(null=True),
        ),
    ]
