# Generated by Django 4.1.1 on 2022-11-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0044_alter_restaurante_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='releasedate',
            field=models.DateTimeField(null=True),
        ),
    ]
