# Generated by Django 4.1.1 on 2022-11-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0045_alter_estacionamento_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praiaequip',
            name='releasedate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='releasedate',
            field=models.DateTimeField(null=True),
        ),
    ]
