# Generated by Django 4.1.1 on 2022-11-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0046_alter_praiaequip_releasedate_alter_spot_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fimdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='inidate',
            field=models.DateTimeField(null=True),
        ),
    ]
