# Generated by Django 4.1.2 on 2022-11-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0052_alter_praiaequip_releasedate_alter_reserva_fimdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='releasedate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='praiaequip',
            name='releasedate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fimdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='inidate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='releasedate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='spot',
            name='releasedate',
            field=models.DateTimeField(),
        ),
    ]
