# Generated by Django 4.1.2 on 2022-11-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0053_alter_estacionamento_releasedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='lugares',
            field=models.IntegerField(default=''),
        ),
    ]
