# Generated by Django 4.1.1 on 2022-11-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0055_alter_restaurante_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='pratos',
        ),
        migrations.AddField(
            model_name='menu',
            name='pratos',
            field=models.ManyToManyField(to='basedailym8.pratos'),
        ),
    ]
