# Generated by Django 4.1.1 on 2022-11-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0056_remove_menu_pratos_menu_pratos'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='Menu_image',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to=''),
        ),
    ]
