# Generated by Django 4.1.1 on 2022-11-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0057_restaurante_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='type',
            field=models.CharField(choices=[('Almoço', 'almoco'), ('Lanche', 'lanche'), ('Jantar', 'jantar'), ('Beber um Copo', 'copo')], max_length=20),
        ),
    ]
