# Generated by Django 4.1.1 on 2022-11-06 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0059_remove_spot_estacionamento_remove_spot_praiaequip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praiaequip',
            name='name',
        ),
    ]
