# Generated by Django 4.1.1 on 2022-11-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0060_remove_praiaequip_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='praiaequip',
            old_name='lugares',
            new_name='equipamentos',
        ),
    ]
