# Generated by Django 4.1.1 on 2022-11-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0061_rename_lugares_praiaequip_equipamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='featured_image',
            field=models.ImageField(blank=True, default='logosemfundo.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='featured_image',
            field=models.ImageField(blank=True, default='logosemfundo.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='praiaequip',
            name='featured_image',
            field=models.ImageField(blank=True, default='logosemfundo.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pratos',
            name='featured_image',
            field=models.ImageField(blank=True, default='logosemfundo.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='featured_image',
            field=models.ImageField(blank=True, default='logosemfundo.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='spot',
            name='featured_image',
            field=models.ImageField(blank=True, default='logosemfundo.png', null=True, upload_to=''),
        ),
    ]
