# Generated by Django 4.1.1 on 2022-11-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedailym8', '0062_alter_estacionamento_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praia',
            name='NumeroEquipamentos',
        ),
    ]
